# Generated by Django 3.1.5 on 2021-01-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='country',
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='none.', max_length=50),
        ),
    ]
