# Generated by Django 3.1.5 on 2021-01-31 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20210129_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='full_name',
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='none.', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_dispatch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='order_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='reg_plate',
            field=models.CharField(default='none.', max_length=32),
        ),
    ]
