# Generated by Django 3.1.5 on 2021-01-31 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_auto_20210131_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reg_plate',
            field=models.ManyToManyField(blank=True, related_name='order_reg_plate', to='checkout.RegPlate'),
        ),
    ]
