# Generated by Django 3.1.5 on 2021-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_auto_20210131_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='regplate',
            name='quantity',
            field=models.CharField(default='none.', max_length=10),
        ),
    ]
